In [15]:
from utils import *
from heuristics import *

In [24]:
from utils import *
from preprocessing import *
import numpy as np
from heuristics import *
### Heuristic of checking hop-1 and hop-2 infections on PA network with avg 5 edges for each node ###
T = 15
PA = True
edges = get_Edges("",PA=True, PA_num=3)
subset_size = 0.3    # at each time step, subset_size of the edges interacted from the whole graph 
infect_rate = 0.05
k = 100
delay =5
if PA:
    node_status = status_setup(1000,infect_rate)
temporal_edges = sample(T, edges, subset_size)
t_edges_index = temporal_edges[:,:,0:2].astype(int)
t_edges_attr =  temporal_edges[:,:,2]


infected_index = np.where(node_status[:,2] == 1)[0]

detection_rate = np.zeros(T)
total_summary_healthy = np.zeros(T)
# Examining infected neighbors 
for t in range(T):
    print("-------------------")
    print("t = ",t)
    if t!=0:
        SEIR_update(node_status,t_edges_index[t-1], t_edges_attr[t-1],t,delay)
    #status_summary(node_status)
    #adj_lst = Adjacency_List("data/ca-GrQc.txt")
    
    adj_lst = Adjacency_List("",arr = t_edges_index[t])
    test_lst = infected_neigh(adj_lst,infected_index,k)
    for n in test_lst:
        if node_status[n,2]==1:
            node_status[n,2]=0
            node_status[n,-1]=1
            detection_rate[t]+=1
        elif node_status[n,1]>0:
            node_status[n,1]=0
            node_status[n,-1]=1
            detection_rate[t]+=1
    total_summary_healthy[t],_,_,_ = status_summary(node_status)

detection_rate = detection_rate/k

-------------------
t =  0
-------------------
t =  1
-------------------
t =  2
-------------------
t =  3
-------------------
t =  4
-------------------
t =  5
-------------------
t =  6
-------------------
t =  7
-------------------
t =  8
-------------------
t =  9
-------------------
t =  10
-------------------
t =  11
-------------------
t =  12
-------------------
t =  13
-------------------
t =  14


In [25]:
list(total_summary_healthy/1000)

[0.959,
 0.891,
 0.836,
 0.741,
 0.651,
 0.516,
 0.408,
 0.283,
 0.205,
 0.128,
 0.082,
 0.054,
 0.023,
 0.016,
 0.014]

In [97]:
list(detection_rate)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [8]:
detection_rate = detection_rate/k

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [23]:
import torch

In [32]:
probability = k_node_sample_prob(torch.tensor([1,4,3,5,3,3,4,2,3,2]))

In [31]:
node_status = status_setup(10,0.2)


In [35]:
node_status[1,3]=1
node_status[-1,3]=1


In [36]:
isolated_index = np.where(node_status[:,3] == 1)[0]


In [37]:
isolated_index

array([1, 9])

In [38]:
probability

tensor([0.0005, 0.1498, 0.1000, 0.1995, 0.1000, 0.1000, 0.1498, 0.0502, 0.1000,
        0.0502])

In [39]:
probability[isolated_index]=0

In [40]:
probability

tensor([0.0005, 0.0000, 0.1000, 0.1995, 0.1000, 0.1000, 0.1498, 0.0502, 0.1000,
        0.0000])

In [72]:
barabasi_albert_graph(1000, 5).t().numpy()

array([[  0,   6],
       [  0,   7],
       [  0,   8],
       ...,
       [999, 290],
       [999, 300],
       [999, 466]])

In [10]:
r = torch.rand(4,4)

In [ ]:
n = np.asarray([1,2])

In [12]:
r

tensor([[0.3732, 0.5803, 0.6686, 0.5344],
        [0.4519, 0.9871, 0.9970, 0.6567],
        [0.7766, 0.7772, 0.9607, 0.1897],
        [0.2886, 0.0929, 0.9385, 0.7903]])

In [13]:
r[n,2]=0

In [14]:
r

tensor([[0.3732, 0.5803, 0.6686, 0.5344],
        [0.4519, 0.9871, 0.0000, 0.6567],
        [0.7766, 0.7772, 0.0000, 0.1897],
        [0.2886, 0.0929, 0.9385, 0.7903]])

In [74]:
from utils import *
from preprocessing import *
import numpy as np
from heuristics import *

### Heuristic of checking hop-1 and hop-2 infections on collaboration network ###

T = 15
subset_size = 0.3    # at each time step, subset_size of the edges interacted from the whole graph 
infect_rate = 0.1
k = 100
delay =5


edges = get_Edges("data/ca-GrQc.txt")
with open('node_features.npy', 'rb') as f:
    node_features = np.load(f)


node_status = status_setup(len(node_features),infect_rate)
temporal_edges = sample(T, edges, subset_size)
t_edges_index = temporal_edges[:,:,0:2].astype(int)
t_edges_attr =  temporal_edges[:,:,2]


infected_index = np.where(node_status[:,2] == 1)[0]

detection_rate = np.zeros(T)
total_summary_healthy = np.zeros(T)

# Examining infected neighbors 
for t in range(T):
    print("-------------------")
    print("t = ",t)
    if t!=0:
        SEIR_update(node_status,t_edges_index[t-1], t_edges_attr[t-1],t,delay)
    status_summary(node_status)
    adj_lst = Adjacency_List("data/ca-GrQc.txt")
    adj_lst = Adjacency_List("",arr = t_edges_index[t])
    test_lst = infected_neigh(adj_lst,infected_index,k)
    for n in test_lst:
        if node_status[n,2]==1:
            node_status[n,2]=0
            node_status[n,-1]=1
            detection_rate[t]+=1
        elif node_status[n,1]>0:
            node_status[n,1]=0
            node_status[n,-1]=1
            detection_rate[t]+=1
    total_summary_healthy[t],_,_,_ = status_summary(node_status)

detection_rate = detection_rate/k

-------------------
t =  0
-------------------
t =  1
-------------------
t =  2
-------------------
t =  3
-------------------
t =  4
-------------------
t =  5
-------------------
t =  6
-------------------
t =  7
-------------------
t =  8
-------------------
t =  9
-------------------
t =  10
-------------------
t =  11
-------------------
t =  12
-------------------
t =  13
-------------------
t =  14


In [75]:
total_summary_healthy/5242

array([0.89622282, 0.81190385, 0.75162152, 0.65223197, 0.56982068,
       0.48550172, 0.41549027, 0.36035864, 0.31228539, 0.27813812,
       0.25333842, 0.23178176, 0.21709271, 0.20144983, 0.19114842])

In [6]:
import torch
from torch_geometric.nn import GCNConv, MessagePassing,Sequential, NNConv
from torch_geometric.nn import NNConv
import torch.nn as nn

In [7]:
 
rnn = nn.GRU(10, 20, 2)

In [8]:
input = torch.randn(5, 3, 10)

In [9]:
input.shape

torch.Size([5, 3, 10])

In [10]:
h0 = torch.randn(2, 3, 20)

In [12]:
h0.shape

torch.Size([2, 3, 20])

In [13]:
output, hn = rnn(input, h0)

In [2]:
from utils import *
from preprocessing import *
import numpy as np
from heuristics import *

### Each node test every 2 time step / half of the average incubation period ###

T = 15
subset_size = 0.3    # at each time step, subset_size of the edges interacted from the whole graph 
infect_rate = 0.05
k = 100
delay =5


edges = get_Edges("data/ca-GrQc.txt")
with open('node_features.npy', 'rb') as f:
    node_features = np.load(f)


node_status = status_setup(len(node_features),infect_rate)
temporal_edges = sample(T, edges, subset_size)
t_edges_index = temporal_edges[:,:,0:2].astype(int)
t_edges_attr =  temporal_edges[:,:,2]


infected_index = np.where(node_status[:,2] == 1)[0]

detection_rate = np.zeros(T)
total_summary_healthy = np.zeros(T)

initial = np.random.randint(2,size = len(node_status))
# Examining infected neighbors 
for t in range(T):
    print("-------------------")
    print("t = ",t)
    if t!=0:
        SEIR_update(node_status,t_edges_index[t-1], t_edges_attr[t-1],t,delay)
    status_summary(node_status)
    
    
    test_lst = half_incubation(initial,t,k)
    for n in test_lst:
        if node_status[n,2]==1:
            node_status[n,2]=0
            node_status[n,-1]=1
            detection_rate[t]+=1
        elif node_status[n,1]>0:
            node_status[n,1]=0
            node_status[n,-1]=1
            detection_rate[t]+=1
    total_summary_healthy[t],_,_,_ = status_summary(node_status)

detection_rate = detection_rate/k

-------------------
t =  0
-------------------
t =  1
-------------------
t =  2
-------------------
t =  3
-------------------
t =  4
-------------------
t =  5
-------------------
t =  6
-------------------
t =  7
-------------------
t =  8
-------------------
t =  9
-------------------
t =  10
-------------------
t =  11
-------------------
t =  12
-------------------
t =  13
-------------------
t =  14


In [91]:
total_summary_healthy/5242

array([0.94963754, 0.89698588, 0.85997711, 0.78347959, 0.72548646,
       0.65299504, 0.5841282 , 0.51602442, 0.46108356, 0.4112934 ,
       0.37390309, 0.34147272, 0.31705456, 0.29530713, 0.27546738])

In [4]:
9%10==0

False